import Navbar from "../components/Navbar"
import SideMenu from "../components/SideMenu"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "IT Jobs",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  const handleClick = (route) => {
    console.log("clicked", route)
    router.push(route)
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="flex">
          <SideMenu />
          <div className="ml-[20rem] py-8">{children}</div>
        </div>
      </body>
    </html>
  )
}
